<?php
/**
 * Snap Marketing - WooCommerce Product Importer with Programmatic SEO & Copywriting
 * Usage via WP-CLI: wp eval-file wp-content/themes/snap-stitch-theme/import_products.php
 */

if ( ! defined( 'ABSPATH' ) ) {
    $wp_load_path = dirname( __FILE__, 4 ) . '/wp-load.php';
    if ( file_exists( $wp_load_path ) ) {
        error_log("IMPORT TRACE: Booting WordPress via $wp_load_path");
        require_once $wp_load_path;
        error_log("IMPORT TRACE: WordPress successfully booted!");
    } else {
        die( "Error: Cannot load WordPress core. Please run this via WP-CLI: wp eval-file import_products.php\n" );
    }
}

// Ensure WooCommerce is active
error_log("IMPORT TRACE: Checking if WooCommerce is active");
if ( ! class_exists( 'WooCommerce' ) ) {
    die( "Error: WooCommerce is not active.\n" );
}

// Allow WP-CLI or web access with secret key
if ( isset( $_SERVER['HTTP_HOST'] ) || isset( $_SERVER['REQUEST_METHOD'] ) ) {
    if ( ! isset( $_GET['secret_key'] ) || $_GET['secret_key'] !== 'snap123' ) {
        status_header( 403 );
        die( 'Forbidden: Invalid or missing secret key.' );
    }
}

/**
 * Parses raw supplier product titles into clean, structured attributes for SEO.
 */
function parse_bluestar_title( $raw_title, $vendor, $category ) {
    $parts = array_map( 'trim', explode( '|', $raw_title ) );
    
    $capacity    = '';
    $star_rating = '';
    $series      = '';
    $type        = $category;
    
    foreach ( $parts as $part ) {
        // Find capacity (e.g. 1.5 TON, 215 Litres)
        if ( preg_match( '/(\d+(\.\d+)?)\s*(TON|Ton|Litres|Litre|Ltr|L)/i', $part, $matches ) ) {
            $capacity = $matches[0];
        }
        // Find star rating (e.g. 5 STAR, 3 Star)
        elseif ( preg_match( '/(\d+)\s*(STAR|Star)/i', $part, $matches ) ) {
            $star_rating = $matches[1] . ' Star';
        }
        // Identify product type
        elseif ( preg_match( '/(Deep Freezer|Air Conditioner|AC|Cooler|Water Dispenser)/i', $part, $matches ) ) {
            $type = $matches[1];
        }
        // Series matches
        elseif ( stripos( $part, 'Series' ) !== false ) {
            $series = $part;
        }
        // Fallback for series / additional descriptive details
        elseif ( empty( $series ) && strlen( $part ) > 3 && ! preg_match( '/2026/i', $part ) ) {
            $series = $part;
        }
    }
    
    if ( empty( $type ) ) {
        $type = 'Unit';
    }
    
    // Normalize Type
    if ( stripos( $type, 'AC' ) !== false || stripos( $type, 'Air Conditioner' ) !== false ) {
        $type = 'Inverter Split AC';
    }
    
    if ( ! empty( $series ) ) {
        $series = preg_replace( '/(Deep Freezer|Air Conditioner|AC|Unit)/i', '', $series );
        $series = trim( $series, ' -|' );
    }
    
    return array(
        'capacity'    => trim( $capacity ),
        'star_rating' => trim( $star_rating ),
        'series'      => trim( $series ),
        'type'        => trim( $type ),
        'vendor'      => ! empty( $vendor ) ? $vendor : 'Blue Star'
    );
}

// Path to the JSON file generated by our Python scraper (theme-relative for Docker visibility)
$json_file = dirname( __FILE__ ) . '/products.json';

if ( ! file_exists( $json_file ) ) {
    die( "Error: JSON file not found at {$json_file}\n" );
}

echo "Starting WooCommerce Product Import with Programmatic SEO...\n";
echo "Reading data from: {$json_file}\n";
error_log("IMPORT TRACE: Reading JSON file");

$json_data = file_get_contents( $json_file );
$products  = json_decode( $json_data, true );

if ( ! $products || ! is_array( $products ) ) {
    die( "Error: Invalid JSON format.\n" );
}

// Parse CLI arguments if run via CLI/WP-CLI
$limit = -1;
$dry_run = false;

if ( isset( $GLOBALS['argv'] ) ) {
    foreach ( $GLOBALS['argv'] as $arg ) {
        if ( preg_match( '/^(?:--)?limit=(\d+)$/', $arg, $matches ) ) {
            $limit = intval( $matches[1] );
        }
        if ( in_array( $arg, array( '--dry-run', 'dry-run', 'dry_run' ), true ) ) {
            $dry_run = true;
        }
    }
} elseif ( isset( $_GET['limit'] ) ) {
    $limit = intval( $_GET['limit'] );
    if ( isset( $_GET['dry_run'] ) ) {
        $dry_run = true;
    }
}

if ( $dry_run ) {
    echo "DRY-RUN MODE ACTIVE: No database changes will be made.\n";
}

$imported = 0;
$skipped  = 0;
$processed_count = 0;

error_log("IMPORT TRACE: Entering foreach loop with " . count($products) . " products");

foreach ( $products as $item ) {
    error_log("IMPORT TRACE: Start processing item " . ($processed_count + 1));
    if ( $limit > 0 && $processed_count >= $limit ) {
        echo "Limit of {$limit} products reached. Stopping import.\n";
        break;
    }
    $processed_count++;

    $raw_title = sanitize_text_field( $item['post_title'] );
    $sku       = sanitize_text_field( $item['sku'] );
    $price     = sanitize_text_field( $item['regular_price'] );
    $category  = sanitize_text_field( $item['category'] );
    $tags      = sanitize_text_field( $item['tags'] );
    $image_url = esc_url_raw( $item['image_url'] );
    $vendor    = sanitize_text_field( $item['vendor'] );

    // Apply programmatic SEO parser to convert raw titles to search-intent optimized titles
    $seo_attrs = parse_bluestar_title( $raw_title, $vendor, $category );
    
    // Build Clean title: Blue Star 1.5 Ton 5 Star Inverter Split AC (Z Smart Wi-Fi Series)
    $title_parts = array( $seo_attrs['vendor'] );
    if ( ! empty( $seo_attrs['capacity'] ) ) {
        $title_parts[] = $seo_attrs['capacity'];
    }
    if ( ! empty( $seo_attrs['star_rating'] ) ) {
        $title_parts[] = $seo_attrs['star_rating'];
    }
    $title_parts[] = $seo_attrs['type'];
    
    $clean_title = implode( ' ', $title_parts );
    if ( ! empty( $seo_attrs['series'] ) ) {
        $clean_title .= " ({$seo_attrs['series']})";
    }
    
    $clean_title = sanitize_text_field( $clean_title );

    echo "Processing: {$clean_title} (SKU: {$sku})... ";
    error_log("IMPORT TRACE: Checking if SKU exists: $sku");

    // Prevent duplicates: Check if SKU exists
    if ( ! empty( $sku ) && wc_get_product_id_by_sku( $sku ) ) {
        echo "SKIPPED (SKU already exists)\n";
        $skipped++;
        continue;
    }

    // Prevent duplicates: Check if Title already exists
    $existing_product = get_page_by_title( $clean_title, OBJECT, 'product' );
    if ( $existing_product ) {
        echo "SKIPPED (Title already exists)\n";
        $skipped++;
        continue;
    }

    // Build Copywriting & Conversion-Optimized Descriptions
    $excerpt = "Upgrade your space with the energy-efficient {$seo_attrs['vendor']} {$seo_attrs['type']}. Featuring a {$seo_attrs['capacity']} capacity and {$seo_attrs['star_rating']} efficiency, this unit is engineered for reliable, durable performance.";
    if ( ! empty( $seo_attrs['series'] ) ) {
        $excerpt .= " Part of the premium {$seo_attrs['series']} lineup.";
    }

    $description_html = "<h3>Premium Cooling & Refrigeration Solutions</h3>";
    $description_html .= "<p>Maximize comfort and efficiency with the <strong>{$clean_title}</strong>, designed by {$seo_attrs['vendor']}. Ideal for residential and commercial use, this model incorporates state-of-the-art cooling technology to ensure consistent temperature control even in extreme climates.</p>";
    $description_html .= "<h4>Why Choose This Model?</h4>";
    $description_html .= "<ul>";
    if ( ! empty( $seo_attrs['capacity'] ) ) {
        $description_html .= "<li><strong>Sizing & Capacity:</strong> Optimized {$seo_attrs['capacity']} capacity fits standard room sizing perfectly.</li>";
    }
    if ( ! empty( $seo_attrs['star_rating'] ) ) {
        $description_html .= "<li><strong>High Efficiency:</strong> Highly rated {$seo_attrs['star_rating']} energy efficiency keeps operating costs low.</li>";
    }
    if ( ! empty( $seo_attrs['series'] ) ) {
        $description_html .= "<li><strong>Intelligent Features:</strong> Designed under the {$seo_attrs['series']} framework for modern user controls.</li>";
    }
    $description_html .= "<li><strong>Build Quality:</strong> Engineered using durable, rust-resistant materials for a longer operational lifecycle.</li>";
    $description_html .= "</ul>";

    // Build SEO Meta Values
    $seo_meta_title = "Buy {$clean_title} Online - Snap Marketing";
    $seo_meta_desc  = "Get the best deal on the {$clean_title}. Buy online from Snap Marketing for official brand warranty, fast delivery, and expert customer support.";

    if ( $dry_run ) {
        echo "DRY-RUN SUCCESS\n";
        echo "   Clean Title: {$clean_title}\n";
        echo "   SKU:         {$sku}\n";
        echo "   Price:       {$price}\n";
        echo "   Category:    {$category}\n";
        echo "   SEO Title:   {$seo_meta_title}\n";
        echo "   SEO Desc:    {$seo_meta_desc}\n";
        echo "   Excerpt:     {$excerpt}\n";
        echo "   Desc:        " . substr( strip_tags( $description_html ), 0, 100 ) . "...\n";
        $imported++;
        continue;
    }

    try {
        // Create a new simple product
        $product = new WC_Product_Simple();
        $product->set_name( $clean_title );
        $product->set_status( 'draft' ); // Start as draft for safety
        $product->set_catalog_visibility( 'visible' );
        $product->set_description( $description_html );
        $product->set_short_description( $excerpt );
        
        if ( ! empty( $sku ) ) {
            $product->set_sku( $sku );
        }
        
        if ( ! empty( $price ) && $price > 0 ) {
            $product->set_regular_price( $price );
            $product->set_price( $price );
        }

        // Handle Categories
        if ( ! empty( $category ) ) {
            $term = term_exists( $category, 'product_cat' );
            if ( ! $term ) {
                $term = wp_insert_term( $category, 'product_cat' );
            }
            if ( ! is_wp_error( $term ) ) {
                $product->set_category_ids( array( $term['term_id'] ) );
            }
        }

        // Handle Tags
        if ( ! empty( $tags ) ) {
            $tag_names = explode( ',', $tags );
            $tag_ids   = array();
            foreach ( $tag_names as $tag_name ) {
                $tag_name = trim( $tag_name );
                if ( empty( $tag_name ) ) continue;
                
                $term = term_exists( $tag_name, 'product_tag' );
                if ( ! $term ) {
                    $term = wp_insert_term( $tag_name, 'product_tag' );
                }
                if ( ! is_wp_error( $term ) ) {
                    $tag_ids[] = $term['term_id'];
                }
            }
            if ( ! empty( $tag_ids ) ) {
                $product->set_tag_ids( $tag_ids );
            }
        }

        // Save product to generate an ID
        $product_id = $product->save();

        if ( $product_id ) {
            // Sideload RankMath Meta Keys
            update_post_meta( $product_id, 'rank_math_title', $seo_meta_title );
            update_post_meta( $product_id, 'rank_math_description', $seo_meta_desc );
            update_post_meta( $product_id, 'rank_math_robots', array( 'index' ) );

            // Sideload Yoast SEO Meta Keys (as backup)
            update_post_meta( $product_id, '_yoast_wpseo_title', $seo_meta_title );
            update_post_meta( $product_id, '_yoast_wpseo_metadesc', $seo_meta_desc );

            // Handle B2B Brochure PDF
            if ( isset( $item['brochure_url'] ) && ! empty( $item['brochure_url'] ) ) {
                $brochure_url = sanitize_text_field( $item['brochure_url'] );
                update_post_meta( $product_id, '_brochure_url', $brochure_url );
            }

            // Handle Image Sideloading
            if ( ! empty( $image_url ) ) {
                require_once( ABSPATH . 'wp-admin/includes/media.php' );
                require_once( ABSPATH . 'wp-admin/includes/file.php' );
                require_once( ABSPATH . 'wp-admin/includes/image.php' );

                // Clean the title for alt/caption matching
                $image_alt = "{$clean_title} - Snap Marketing";
                $attachment_id = media_sideload_image( $image_url, $product_id, $image_alt, 'id' );
                
                if ( ! is_wp_error( $attachment_id ) ) {
                    $product->set_image_id( $attachment_id );
                    
                    // Set Alt Text on media attachment directly for maximum search visibility
                    update_post_meta( $attachment_id, '_wp_attachment_image_alt', $image_alt );
                    
                    $product->save();
                    echo "SUCCESS (with SEO & Image)\n";
                } else {
                    echo "SUCCESS (with SEO, Image sideload failed: " . $attachment_id->get_error_message() . ")\n";
                }
            } else {
                echo "SUCCESS (with SEO)\n";
            }
            $imported++;
        }

    } catch ( Exception $e ) {
        echo "FAILED (" . $e->getMessage() . ")\n";
    }
}

echo "\nImport Complete!\n";
echo "Total Imported: {$imported}\n";
echo "Total Skipped: {$skipped}\n";

